### ISSUE TITLE
BUG: postette.done() should silently cancel a spinner

### ISSUE THREAD

**Issue by bryanressler-idmod** [ptrdo/postette#1]
postette.done(), with no arguments, doesn't actually do anything. It should silently cancel a spinner with no message - just make the spinner go away. The fact that it doesn't do anything seems like a bug.

Currently the only workaround seems to be

postette.notify("Complete.", { level: "success", delay: -1 });

Which puts up a Complete message, which I don't really want.

**Comment by ptrdo** [comment]
The original design was to provide a means of dialog between the application and its user, and in that respect, using Postette as a conventional “spinner” (which blocks interaction and then goes away silently) sort of breaks that paradigm for communication. The idea should be that a persisting state represents an unknown duration of background process with a completion that is of interest to the user (a success or fail). Also, any click will dismiss a persisting message, as will a subsequent message that's been set to move the queue, so the Postette “spinner” does not technically suspend interaction as would be expected of its conventional cousin. 

However, the public convenience method being named “spinner” is a bit of a misnomer, and it DOES make sense that a notification of any type or duration should be cancelable without fanfare (this has been requested before). But rather than modifying “done” (which suggests a completing event), let's make a new “dismiss” method which will essentially quietly close any current message with a remote triggering of the clickHandler.

**Comment by ptrdo** [comment]
Release v0.3.0 now includes a public instance method `dismiss();` which programmatically closes any current message (effectively the same result as click-to-close or click-away). Thanks for the bug!
